# Generated by Django 4.1.6 on 2024-02-03 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_payment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='quantity_sold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.sale'),
        ),
    ]
