# Generated by Django 4.1.6 on 2024-02-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_payment_quantity_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='product',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='quantity_sold',
        ),
    ]
